"""Increase password_hash length

Revision ID: 54533b262d35
Revises: 82a61adf8b06
Create Date: 2024-02-25 20:53:43.427562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54533b262d35'
down_revision = '82a61adf8b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
